# Generated by Django 2.2 on 2019-09-05 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denma_subscribe_form', '0001_initial'),
        ('denma_contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='subscribe_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subscribed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_user', to='denma_subscribe_form.SubscribedUser'),
        ),
    ]
