# Generated by Django 2.2 on 2019-09-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denma_contact_form', '0002_auto_20190905_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='subscribed_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_user', to='denma_subscribe_form.SubscribedUser'),
        ),
    ]
