# Generated by Django 2.2 on 2019-09-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denma_contact_form', '0003_auto_20190905_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='subscribed_user',
        ),
    ]
